[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore BunnyChat/BunnyChat.csproj"]

[phases.build]
cmds = ["dotnet publish BunnyChat/BunnyChat.csproj -c Release -o out --no-restore"]

[start]
cmd = "dotnet out/BunnyChat.dll"
