[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore BunnyChat.csproj"]

[phases.build]
cmds = ["dotnet publish BunnyChat.csproj -c Release -r linux-x64 --self-contained true -o out --no-restore"]

[start]
cmd = "./out/BunnyChat"
